sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Generator Production"
    id: daily_generator_production
    register_type: holding
    address: 62
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:generator-portable"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Generator Production"
    id: total_generator_production
    register_type: holding
    address: 92
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator L1 Voltage"
    id: generator_l1_voltage
    register_type: holding
    address: 181
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:lightning-bolt"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Frequency"
    register_type: holding
    address: 196
    unit_of_measurement: "Hz"
    device_class: frequency

    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Power Total"
    id: generator_power_total
    register_type: holding
    address: 166
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:engine"

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Port Use"
    address: 235
    value_type: U_WORD
    entity_category: config
    icon: "mdi:connection"
    optionsmap:
      "Generator Input": 0
      "SmartLoad Output": 1
      "Micro Inverter Input": 2

number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad Off Voltage"
    address: 236
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad Off SOC"
    address: 237
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad On Voltage"
    address: 238
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 38
    max_value: 63
    step: 0.01
    entity_category: config
    icon: "mdi:lightning-bolt-circle"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "SmartLoad On SOC"
    address: 239
    unit_of_measurement: "%"
    value_type: U_WORD
    min_value: 0
    max_value: 100
    step: 1
    entity_category: config
    icon: "mdi:lightning-bolt-circle"
