# Copyright 2025 Lewa-Reka & Harvey Dent
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L1 Power"
    register_type: holding
    address: 167
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L2 Power"
    register_type: holding
    address: 168
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Power"
    register_type: holding
    address: 169
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Frequency"
    register_type: holding
    address: 79
    unit_of_measurement: "Hz"
    device_class: frequency
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L1 Voltage"
    id: grid_voltage_l1
    register_type: holding
    address: 150
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L2 Voltage"
    id: grid_voltage_l2
    register_type: holding
    address: 151
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Voltage"
    id: grid_voltage
    register_type: holding
    address: 152
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave" 

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Energy Bought"
    id: daily_energy_bought
    register_type: holding
    address: 76
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Energy Sold"
    id: daily_energy_sold
    register_type: holding
    address: 77
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-export"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Energy Bought"
    id: total_energy_bought
    register_type: holding
    address: 78
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Energy Sold"
    id: total_energy_sold
    register_type: holding
    address: 81
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-export"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L1 Power"
    register_type: holding
    address: 170
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L2 Power"
    register_type: holding
    address: 171
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT Power"
    register_type: holding
    address: 172
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L1 Current"
    id: external_ct_l1_current
    register_type: holding
    address: 162
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L2 Current"
    id: external_ct_l2_current
    register_type: holding
    address: 163
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Frequency"
    address: 285
    value_type: U_WORD
    entity_category: config
    icon: "mdi:sine-wave"
    optionsmap:
      "50 Hz": 0
      "60 Hz": 1

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Charging Signal"
    address: 242
    value_type: U_WORD
    entity_category: config
    icon: "mdi:battery-charging"
    optionsmap:
      "Normal": 0
      "Grid": 1
      "Generator": 2
      "Both": 3

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Force Off Grid test"
    id: switch_off_grid
    register_type: holding
    address: 281
    bitmask: 1
    entity_category: config
    icon: "mdi:transmission-tower-off"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Grid Side"
    register_type: holding
    address: 280
    bitmask: 12 
    entity_category: config
    icon: "mdi:generator-stationary"

number: 
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: grid_voltage_protection_high
    name: "Grid voltage protection - high"
    unit_of_measurement: "V"
    device_class: voltage
    entity_category: config
    register_type: holding
    multiply: 10
    min_value: 100
    max_value: 280
    step: 1
    address: 287
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: grid_voltage_protection_low
    name: "Grid voltage protection - low"
    unit_of_measurement: "V"
    device_class: voltage
    entity_category: config
    register_type: holding
    min_value: 100
    max_value: 288
    step: 1
    address: 287
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: grid_requency_protection_high
    name: "Grid Frequency Protection - high"
    unit_of_measurement: "Hz"
    device_class: frequency
    entity_category: config
    register_type: holding
    min_value: 45
    max_value: 65
    step: 1
    address: 289
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: grid_requency_protection_low
    name: "Grid Frequency Protection - low"
    unit_of_measurement: "Hz"
    device_class: frequency
    entity_category: config
    register_type: holding
    min_value: 45
    max_value: 65
    step: 1
    address: 290
    value_type: U_WORD
    icon: "mdi:sine-wave"

