substitutions:
  name: deye-inverter
  friendly_name: "Deye Inverter"
  device_description: "Deye Inverter SG0XLP1"
  modbus_controller_id: deye_modbus_controller
  baud_rate: "9600"
  # Safe Mode Default parameters
  default_maximum_battery_charge_current: "100" # Amps
  default_max_sell_power: "0" # Watts
  default_system_work_mode: "Zero Export To CT" # "Selling First", "Zero Export To Load", "Zero Export To CT"
  default_solar_sell: "off" # "on", "off"

packages:
  init: !include packages/init.yaml
  battery: !include packages/deye_hybrid_1p/battery.yaml
  gen: !include packages/deye_hybrid_1p/gen.yaml
  grid: !include packages/deye_hybrid_1p/grid.yaml
  load: !include packages/deye_hybrid_1p/load.yaml
  work_mode: !include packages/deye_hybrid_1p/work_mode.yaml
  device: !include packages/deye_hybrid_1p/device.yaml
  inverter: !include packages/deye_hybrid_1p/inverter.yaml
  pv: !include packages/deye_hybrid_1p/pv.yaml
  tou: !include packages/deye_hybrid_1p/tou.yaml

script:
  - id: set_safe_modbus_registers
    then:
      - logger.log:
          level: INFO
          format: "Setting safe Modbus register values"
      - number.set:
          id: maximum_battery_charge_current
          value: ${default_maximum_battery_charge_current}
      - number.set:
          id: max_sell_power
          value: ${default_max_sell_power}
      - select.set:
          id: system_work_mode
          option: ${default_system_work_mode}
      - switch.turn_${default_solar_sell}:
          id: switch_solar_sell
